ECommerce-master/Controllers/contactController.cs
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class contactController : Controller
    {
        myDbContext context = new myDbContext();    
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult contact()
        {
            if (HttpContext.Session.GetInt32("customerId") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("login", "customer"); 
            }
        }
        [HttpPost]
        public IActionResult contact(contact c)
        {
            
            if (c != null && HttpContext.Session.GetInt32("customerId") !=null)
            {
                c.customer_id = (int)HttpContext.Session.GetInt32("customerId");

                context.contacts.Add(c);
                context.SaveChanges();
            }
            return RedirectToAction("show", "product");
        }
        
        public IActionResult about()
        {
            return View();
        }

    }
}

ECommerce-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="customer" asp-action="Register">Register</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="customer" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container d-flex justify-content-center shadow-none p-3 mb-5 bg-light rounded" style="background-color: #eee ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ECommerce-master/Views/Shared/_mainLayout.cshtml
@{
    Layout = null;
    int? customerId = Context.Session.GetInt32("customerId");
    int? isAdmin = Context.Session.GetInt32("isAdmin");

    string? customerName = Context.Session.GetString("customerName");

}

<!DOCTYPE html>

<html>

<head>
   <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/css/bootstrap.min.css" integrity="sha512-6KY5s6UI5J7SVYuZB4S/CZMyPylqyyNZco376NM2Z8Sb8OxEdp02e1jkKk/wZxIEmjQ6DRCEBhni+gpr9c4tvA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css " />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <div >
                <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light p-4" style="background-color:#DFDFCF">
          <!-- Container wrapper -->
          <div class="container-fluid">
            <!-- Toggle button -->
            <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Navbar brand -->
              <a class="navbar-brand mt-2 mt-lg-0 h5" asp-action="show" asp-controller="product">
                ECommerce
              </a>
              <!-- Left links -->
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               
                <li class="nav-item">
                  <a class="nav-link h5" asp-action="show" asp-controller="product">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link h5" asp-action="about" asp-controller="contact">About Us</a>
                </li>
                
                <li class="nav-item nav-link "> 
                </li> 
                @if (isAdmin == 1)
                {
                    <li class="nav-item">
                            <a class="nav-link h5" asp-action="show_problem" asp-controller="customer">Customers Problem</a>
                    </li>
                }
                @if (customerId == null)
                {
                <li class="nav-item">
                    <a class="nav-link h5" asp-action="Login" asp-controller="customer">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link h5" asp-action="Register" asp-controller="customer">Register</a>
                </li>
                    }else{
                        <li class="nav-item">
                            <a class="nav-link h5" asp-action="contact" asp-controller="contact">Contact Us</a>
                        </li>
                    }
            </ul>

              <!-- Left links -->
            </div>
            <!-- Collapsible wrapper -->
            
                    <div style="margin-right:50px;">
                        <form class="d-flex input-group w-150" style="width:450px">
                <input
                  type="search"
                  class="form-control"
                  placeholder="Search here !"
                  aria-label="Search"
                  width="100px"
                />
                <button
                  class="btn btn-outline-primary"
                  type="button"
                  data-mdb-ripple-color="dark"
                >
                  Search
                </button>
              </form>
           </div>
                @if (customerId != null)
                {
            <!-- Right elements -->
            <div class="d-flex align-items-center "  >
              <!-- Icon -->
                  <a class="text-reset me-3" asp-action="view" asp-controller="Cart">
                      Cart
                  <span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                     <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                </span>
              </a>

              <a class="text-reset me-3" style="margin-left:20px;" asp-action="details" asp-controller="customer">
                      @customerName
                 <span >
                         <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                          <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                        </svg>
                 </span>
                </a>
                          <a class="text-reset me-3" style="margin-left:20px;" asp-action="logout" asp-controller="customer">
                          Logout
                     <span >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                          <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                        </svg>                  
                    </span>
                    </a>
              </div>
              <!-- Avatar -->
              
              

                   @* <div class="dropdown ">
                        <a 
                    style="margin-left:10px"
                  class="dropdown-toggle d-flex align-items-center hidden-arrow"
                  href="#"
                  role="button"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false"
                >
                            <img
                    src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                    class="rounded-circle"
                    height="25"
                    alt="Black and White Portrait of a Man"
                    loading="lazy"
                  />
                       
                        </a>
                          
                        <ul
                  class="dropdown-menu dropdown-menu-end"
                  aria-labelledby="navbarDropdownMenuAvatar"
                >
                            <li>
                                <a class="dropdown-item" href="#">My profile</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Logout</a>
                            </li>
                        </ul>
                    </div>*@
                    }
                    </div>
                    <!-- Right elements -->
                    </div>
                    <!-- Container wrapper -->

                

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>

     <div class="container d-flex justify-content-center shadow-none p-3 mb-5 bg-light rounded" style="background-color: #eee ">
        <main role="main" class="w-100">
            @RenderBody()
        </main>
    </div>
    <div>
       @* <footer class="text-center text-white fixed-bottom" style="background-color: #21081a;">
  <!-- Grid container -->
  <div class="container p-4"></div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="#">ECommerce</a>
  </div>
  <!-- Copyright -->
</footer>*@
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
    @await this.RenderSectionAsync("Charts", required: false)
</body>
</html>